# Generated by Django 2.2.1 on 2019-05-24 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('devid_id', models.IntegerField(blank=True, null=True)),
                ('job_suite_name', models.CharField(max_length=50)),
                ('job_cass_name', models.CharField(max_length=50)),
                ('job_case_result', models.CharField(max_length=10)),
                ('job_cass_log', models.TextField(null=True)),
                ('job_mark', models.TextField(null=True)),
                ('job_log_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 24, 6, 39, 25, 6427), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cpu_used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('devid_id', models.IntegerField()),
                ('door', models.FloatField()),
                ('weigh', models.FloatField()),
                ('weighcv_cm', models.FloatField()),
                ('weighcv_as', models.FloatField()),
                ('iotkit', models.FloatField()),
                ('apps', models.FloatField()),
                ('alarm', models.FloatField()),
                ('monitor', models.FloatField()),
                ('tts', models.FloatField()),
                ('get_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 24, 6, 39, 25, 543), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mem_summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('devid_id', models.IntegerField()),
                ('mem_total', models.IntegerField()),
                ('mem_free', models.IntegerField()),
                ('mem_use', models.IntegerField()),
                ('mem_buff', models.IntegerField()),
                ('remaind_space', models.IntegerField()),
                ('get_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 24, 6, 39, 25, 4273), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mem_used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('devid_id', models.IntegerField()),
                ('door', models.FloatField()),
                ('weigh', models.FloatField()),
                ('weighcv_cm', models.FloatField()),
                ('weighcv_as', models.FloatField()),
                ('iotkit', models.FloatField()),
                ('apps', models.FloatField()),
                ('alarm', models.FloatField()),
                ('monitor', models.FloatField()),
                ('tts', models.FloatField()),
                ('get_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 24, 6, 39, 25, 2993), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='suite_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_suite_name', models.CharField(max_length=50)),
                ('job_case_run_status', models.IntegerField()),
                ('job_run_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 24, 6, 39, 25, 5331), null=True)),
            ],
        ),
    ]
