# Generated by Django 2.2.1 on 2019-05-29 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20190529_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_log',
            name='job_log_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 29, 7, 0, 8, 368006), null=True),
        ),
        migrations.AlterField(
            model_name='cpu_used',
            name='get_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 29, 7, 0, 8, 364551), null=True),
        ),
        migrations.AlterField(
            model_name='mem_summary',
            name='get_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 29, 7, 0, 8, 366565), null=True),
        ),
        migrations.AlterField(
            model_name='mem_used',
            name='get_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 29, 7, 0, 8, 365641), null=True),
        ),
        migrations.AlterField(
            model_name='suite_status',
            name='job_run_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 29, 7, 0, 8, 367246), null=True),
        ),
    ]
